# Generated by Django 4.0 on 2024-02-11 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questx', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='quest',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='questx.quest'),
        ),
    ]
