# Generated by Django 4.0 on 2024-02-28 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questx', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='exps_choices',
            field=models.JSONField(blank=True, default=(), null=True),
        ),
    ]
