# Generated by Django 4.0 on 2024-02-11 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questx', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitymanager',
            name='cm_id',
            field=models.CharField(default='C50956413', editable=False, max_length=9, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='experience',
            name='exp_id',
            field=models.CharField(default='E23718957', editable=False, max_length=9, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='quest',
            name='quest_id',
            field=models.CharField(default='Q40227219', editable=False, max_length=9, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(default='U32501952', editable=False, max_length=9, primary_key=True, serialize=False, unique=True),
        ),
    ]
