# Generated by Django 4.0 on 2024-02-11 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questx', '0002_alter_experience_quest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='quest',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='questx.quest'),
        ),
    ]
