# Generated by Django 4.0 on 2024-02-11 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questx', '0003_alter_communitymanager_cm_id_alter_experience_exp_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitymanager',
            name='cm_id',
            field=models.CharField(default='C98583690', editable=False, max_length=9, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='experience',
            name='exp_id',
            field=models.CharField(default='E32229603', editable=False, max_length=9, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='quest',
            name='quest_id',
            field=models.CharField(default='Q39009632', editable=False, max_length=9, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(default='U93643332', editable=False, max_length=9, primary_key=True, serialize=False, unique=True),
        ),
    ]
