# Generated by Django 4.0 on 2024-02-28 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questx', '0004_alter_quest_exps_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='exps_choices',
            field=models.JSONField(blank=True, choices=[('E96463347', 'Lost Temple Expedition'), ('E63901253', 'Survival Camp in the Wilderness')], null=True),
        ),
    ]
