# Generated by Django 4.0 on 2024-02-11 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questx', '0005_alter_communitymanager_cm_id_alter_experience_exp_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitymanager',
            name='cm_id',
            field=models.CharField(editable=False, max_length=9, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='exp_id',
            field=models.CharField(editable=False, max_length=9, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='quest',
            name='quest_id',
            field=models.CharField(editable=False, max_length=9, primary_key=True, serialize=False, unique=True),
        ),
    ]
