# Generated by Django 4.0 on 2024-02-28 09:14

from django.db import migrations, models
import questx.models


class Migration(migrations.Migration):

    dependencies = [
        ('questx', '0005_alter_quest_exps_choices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quest',
            name='exps_choices',
        ),
        migrations.AlterField(
            model_name='quest',
            name='exp_ids',
            field=models.JSONField(default=list, help_text=(('E96463347', 'Lost Temple Expedition'), ('E63901253', 'Survival Camp in the Wilderness')), validators=[questx.models.ExperienceValidator()]),
        ),
    ]
