# Generated by Django 4.0 on 2024-02-29 11:02

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questx', '0006_remove_quest_exps_choices_alter_quest_exp_ids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='exp_duration',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='exp_preferred_time',
        ),
        migrations.RemoveField(
            model_name='quest',
            name='exp_ids',
        ),
        migrations.AddField(
            model_name='experience',
            name='exp_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='experience',
            name='exp_end_time',
            field=models.PositiveIntegerField(default=18, validators=[django.core.validators.MaxValueValidator(23, 'End time cannot exceed 23')]),
        ),
        migrations.AddField(
            model_name='experience',
            name='exp_start_time',
            field=models.PositiveIntegerField(default=16, validators=[django.core.validators.MaxValueValidator(23, 'Start time cannot exceed 23')]),
        ),
        migrations.AddField(
            model_name='quest',
            name='quest_start_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='quest',
            name='quest_duration',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
