# Generated by Django 4.0 on 2024-02-13 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('member', 'Member'), ('cm', 'Community Manager'), ('admin', 'Admin')], max_length=10),
        ),
    ]
