# Generated by Django 4.0 on 2024-02-13 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=15)),
                ('user_type', models.CharField(choices=[('member', 'Member'), ('cm', 'Community Manager'), ('admin', 'Admin')], max_length=10)),
            ],
        ),
    ]
